version: 2
build:
  os: ubuntu-24.04
  # os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: avi-docs/conf.py


# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

python:
  install:
    - requirements: avi-docs/requirements.txt

# docs:
#   build:
#     image: latest
#     commands:
#       - python -m pip install -r avi-docs/requirements.txt
#       - cd avi-docs && sphinx-build -b html . _build/html

